name: x05 assignment

on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]
    
  jobs:
    install:
      runs-on: ubuntu-latest
      steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -f build-essential g++ cmake
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Build project
        run: |
          g++ main.cpp -std+c++17 -o project-1.cpp
